//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 27/05/2024 15:32:15
//
//===========================================================================================
//
#pragma once

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"etherwake"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"etherwake (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"etherwake (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"etherwake"
#define PROGRAM_REGKEY  L"Macallan\\etherwake"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\etherwake"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "etherwake"
#ifdef _WIN64
#define PROGRAM_NAME_P  "etherwake (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "etherwake (x86 MBCS)"
#endif
#define PROGRAM_SECT    "etherwake"
#define PROGRAM_REGKEY  "Macallan\\etherwake"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\etherwake"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Mon May 27 15:32"
#define PROGRAM_DATE_F  L"Mon May 27 15:32 2024"
#define PROGRAM_YEAR    L"2024"
#define PROGRAM_TIME    L"2024/05/27 15:32:15"
#else
#define PROGRAM_DATE    "Mon May 27 15:32"
#define PROGRAM_DATE_F  "Mon May 27 15:32 2024"
#define PROGRAM_YEAR    "2024"
#define PROGRAM_TIME    "2024/05/27 15:32:15"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"1.0.04.006"
#define PROGRAM_INSTALL L"1.0.04006"
#define PROGRAM_VER_NUM 10004006
#define PROGRAM_BUILD   L"76"
#define PROGRAM_TITLE   L"etherwake"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"etherwake (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"etherwake (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "1.0.04.006"
#define PROGRAM_INSTALL "1.0.04006"
#define PROGRAM_VER_NUM 10004006
#define PROGRAM_BUILD   "76"
#define PROGRAM_TITLE   "etherwake"
#ifdef _WIN64
#define PROGRAM_TITLE_P "etherwake (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "etherwake (x86 MBCS)"
#endif
#endif

